### ISSUE TITLE
Console Is Hard To Read On Linux Due To Color Formatting

### ISSUE THREAD

**Issue by keyphact** [PolarisTeam/PolarisServer#20]
![polaris-console-on-linux](https://cloud.githubusercontent.com/assets/1712363/5589056/cee81ea0-910d-11e4-9b59-6e7c49e42202.png)

The console screen on Linux makes it hard to read due to the color formatting.
Example has been pasted above when an exception comes through, and reading the console in general

Maybe we should either get this working in Linux or remove it altogether?

**Comment by cyberkitsune** [comment]
To note: I've noticed that the colors work fine on linux in most cases. Is there something wrong with your terminal?

**Comment by KeyPhact** [comment]
Hmm are you using PuTTy or an actual terminal on a Linux OS?
I'm getting the above on all versions on my Fedora and CentOs machines.
