### ISSUE TITLE
Licencing Error ?

### ISSUE THREAD

**Issue by Zenohate** [PolarisTeam/PolarisServer#39]
Affero GPL forbids you to connect Polaris without an open sourced version of PSO2. Isn't that an error ?

**Comment by cyberkitsune** [comment]
AGPL protects Polaris when being provided as a service. PSO2's client is receiving the service Polaris is providing, not creating it. Therefore, AGPL only protects and requires that Polaris be open source, not PSO2.

If I'm wrong please cite the legal text from AGPL and let me know and we will relicence :)

**Comment by Zenohate** [comment]
It may be a misunderstanding of the section 13 paragraph 2. Legal terms are Greek to me. It may be in case of provisioning the software as a service like you said. I can't get those things. I should ask a jurist later if you want. ;)

**Comment by Furyhunter** [comment]
That paragraph is referring to _linking_ which is defined as part of the regular GPL license, and does not cover communication with peers. If that were true, then a lot of services not even in the field of server emulation would have their clients required to be GPL, and that really wouldn't make sense. So I believe this is a non-issue.

**Comment by Zenohate** [comment]
Okay, no problem then, always been troubled by licencing issues yet you made it clear so it is OK. Thanks, sorry for disturbing ^-^


________________________________
De : Ronald Kinard <notifications@github.com>
Envoyé : vendredi 25 mars 2016 21:54
À : PolarisTeam/PolarisServer
Cc : Ludovic Lagouardette
Objet : Re: [PolarisServer] Licencing Error ? (#39)


That paragraph is referring to linking which is defined as part of the regular GPL license, and does not cover communication with peers. If that were true, then a lot of services not even in the field of server emulation would have their clients required to be GPL, and that really wouldn't make sense. So I believe this is a non-issue.

-
